# Generated by Django 4.1.1 on 2022-09-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('Matrícula', models.CharField(max_length=12, verbose_name='Matrícula')),
                ('Password', models.CharField(max_length=36)),
            ],
        ),
    ]
