# Generated by Django 4.1.1 on 2022-09-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
